name: Build Windows Standalone EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "5.9.2"
        
    - name: Verify Swift Installation
      run: swift --version
        
    - name: Build Application
      run: |
        swift build --configuration release
        
    - name: Create Portable Distribution
      run: |
        mkdir VACalculator-Portable
        copy .build\release\VACalculatorApp-Windows.exe VACalculator-Portable\
        echo "VA Calculator - Professional Vibration Analysis Tool" > VACalculator-Portable\README.txt
        echo "" >> VACalculator-Portable\README.txt
        echo "To run: Double-click VACalculatorApp-Windows.exe" >> VACalculator-Portable\README.txt
        echo "No installation required!" >> VACalculator-Portable\README.txt
        
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: VACalculator-Windows-Portable
        path: VACalculator-Portable/
        retention-days: 30